enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# --- 非 Root 版本 (APK) ---
[YouTube-NonRoot]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "arm64-v8a"
version = "auto"
excluded-patches = "'Custom branding'"



# --- Root 版本 (Magisk Module) ---
[YouTube-Root]
app-name = "YouTube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"
build-mode = "module"
# Root 版本不需要 GmsCore support (因為是直接掛載於系統)，所以這裡將其排除
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'GmsCore support'"

# --- 其他應用 ---
[GooglePhotos]
build-mode = "module"
arch = "arm64-v8a"
version = "auto"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

#[Tiktok]
#uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
#build-mode = "module"
#included-patches = "'SIM spoof'"
#arch = "arm64-v8a"
